#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.6ubuntu1
dpkg-maintscript-helper rm_conffile /etc/X11/Xsession.d/80qtgraphicssystem 1:12.04ubuntu2 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/grub.d/50_kubuntu.cfg 1:14.04ubuntu15\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/skel/.config/kwinrc 1:18.04ubuntu11 -- "$@"
# End automatically added section
